# Generated by Django 5.1.6 on 2025-02-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_project_documents_alter_project_json_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CLUProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "azure_project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("TRAINED", "Trained"),
                            ("DEPLOYED", "Deployed"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clu_projects",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
