# Generated by Django 5.1.6 on 2025-02-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clu", "0001_initial"),
        ("projects", "0002_project_documents_alter_project_json_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluproject",
            name="azure_project_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cluproject",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cluproject",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clu_project",
                to="projects.project",
            ),
        ),
    ]
