# Generated by Django 5.1.6 on 2025-02-11 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openai_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('azure_project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('json_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='openai_processing.generatedjson')),
            ],
        ),
    ]
