# Generated by Django 5.1.6 on 2025-02-11 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_alter_uploadedpdf_file'),
        ('openai_processing', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(related_name='projects', to='ocr.uploadedpdf'),
        ),
        migrations.AlterField(
            model_name='project',
            name='json_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='openai_processing.generatedjson'),
        ),
    ]
