# Generated by Django 5.1.6 on 2025-02-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openai_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedjson",
            name="json_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
