# Generated by Django 5.1.6 on 2025-02-11 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openai_processing", "0002_generatedjson_json_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedjson",
            name="json_content",
        ),
    ]
