# Generated by Django 5.1.6 on 2025-02-11 10:53

import ocr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(upload_to=ocr.models.pdf_upload_path),
        ),
    ]
